"""sadsadsd

Revision ID: 19af432988e9
Revises: 8501d0059557
Create Date: 2019-01-05 15:19:32.746355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19af432988e9'
down_revision = '8501d0059557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated')
    # ### end Alembic commands ###
